"""add asset external identifiers

Revision ID: 60609e51049c
Revises: f7f1373649a7
Create Date: 2026-10-06 16:09:59.698365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60609e51049c'
down_revision: Union[str, Sequence[str], None] = 'f7f1373649a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_external_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_registry_id', sa.Integer(), nullable=False),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('identifier_value', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_registry_id'], ['asset_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_external_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_external_identifiers_asset_registry_id'), ['asset_registry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_external_identifiers_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_external_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_external_identifiers_id'))
        batch_op.drop_index(batch_op.f('ix_asset_external_identifiers_asset_registry_id'))

    op.drop_table('asset_external_identifiers')
    # ### end Alembic commands ###
