"""create current SAL schema

Revision ID: f7f1373649a7
Revises: 0431066069a0
Create Date: 2026-10-06 10:28:37.080990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f1373649a7'
down_revision: Union[str, Sequence[str], None] = '0431066069a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sal_id', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sal_verification', sa.String(), nullable=True),
    sa.Column('government_verification', sa.String(), nullable=True),
    sa.Column('blockchain_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_registry_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_registry_sal_id'), ['sal_id'], unique=True)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_id'), ['id'], unique=False)

    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('bond_type', sa.String(), nullable=False),
    sa.Column('face_value', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('maturity_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bonds_id'), ['id'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('annual_revenue', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_id'), ['id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('configuration_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_countries_id'), ['id'], unique=False)

    op.create_table('crypto_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('wallet_name', sa.String(), nullable=False),
    sa.Column('blockchain', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('cryptocurrency', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    with op.batch_alter_table('crypto_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crypto_wallets_id'), ['id'], unique=False)

    op.create_table('diamonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('gemstone', sa.String(), nullable=False),
    sa.Column('carat', sa.Float(), nullable=False),
    sa.Column('cut', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('clarity', sa.String(), nullable=False),
    sa.Column('certificate_number', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    with op.batch_alter_table('diamonds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diamonds_id'), ['id'], unique=False)

    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('farm_name', sa.String(), nullable=False),
    sa.Column('farm_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('size_acres', sa.Float(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_id'), ['id'], unique=False)

    op.create_table('gold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('purity', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('gold', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_id'), ['id'], unique=False)

    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('insurer', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_id'), ['id'], unique=False)

    op.create_table('intellectual_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ip_type', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('intellectual_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intellectual_properties_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('asset_transaction_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_asset_transaction_id'), ['asset_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('lands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('community', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('land_use', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_number')
    )
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lands_id'), ['id'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('share_price', sa.Float(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('engine_number', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('vin')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_webhook_event_key')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_event_key'), ['event_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_webhook_events_id'), ['id'], unique=False)

    op.create_table('asset_passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.String(), nullable=False),
    sa.Column('asset_registry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_registry_id'], ['asset_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_passports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_passports_asset_registry_id'), ['asset_registry_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_passports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_passports_passport_id'), ['passport_id'], unique=True)

    op.create_table('government_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_registry_id', sa.Integer(), nullable=False),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_registry_id'], ['asset_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_verifications_asset_registry_id'), ['asset_registry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_verifications_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('billing_type', sa.String(), nullable=True),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_id'), ['id'], unique=False)

    op.create_table('asset_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_backend', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['asset_passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_evidence_evidence_id'), ['evidence_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_evidence_fingerprint_sha256'), ['fingerprint_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_passport_id'), ['passport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_storage_backend'), ['storage_backend'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_storage_key'), ['storage_key'], unique=False)

    op.create_table('asset_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_transactions_id'), ['id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('asset_registry_id', sa.Integer(), nullable=True),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('before_data', sa.String(), nullable=True),
    sa.Column('after_data', sa.String(), nullable=True),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_registry_id'], ['asset_registry.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['asset_passports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_asset_registry_id'), ['asset_registry_id'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)
        batch_op.create_index('ix_audit_events_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_passport_id'), ['passport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_reference'), ['reference'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('passport_lifecycle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['asset_passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passport_lifecycle_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passport_lifecycle_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passport_lifecycle_history_passport_id'), ['passport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passport_lifecycle_history_reference'), ['reference'], unique=True)

    op.create_table('payment_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_audits_id'), ['id'], unique=False)

    op.create_table('payment_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_reconciliations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reconciliations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reconciliations_payment_id'), ['payment_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_receipt_number'), ['receipt_number'], unique=True)

    op.create_table('asset_evidence_review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['asset_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_evidence_review_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_evidence_review_history_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_review_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_evidence_review_history_reference'), ['reference'], unique=False)
        batch_op.create_index('uq_asset_evidence_review_history_reference', ['reference'], unique=True, postgresql_where=sa.text('reference IS NOT NULL'))

    # PostgreSQL database-level immutability for audit events.
    # This mirrors the SQLite protections used by the test database.
    op.execute(sa.text("""
        CREATE OR REPLACE FUNCTION prevent_audit_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                RAISE EXCEPTION 'Audit events are immutable and cannot be updated';
            ELSIF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'Audit events are immutable and cannot be deleted';
            END IF;

            RETURN OLD;
        END;
        $$;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER trg_audit_events_prevent_update
        BEFORE UPDATE ON audit_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_audit_event_mutation();
    """))

    op.execute(sa.text("""
        CREATE TRIGGER trg_audit_events_prevent_delete
        BEFORE DELETE ON audit_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_audit_event_mutation();
    """))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text("""
        DROP TRIGGER IF EXISTS trg_audit_events_prevent_update
        ON audit_events;
    """))

    op.execute(sa.text("""
        DROP TRIGGER IF EXISTS trg_audit_events_prevent_delete
        ON audit_events;
    """))

    op.execute(sa.text("""
        DROP FUNCTION IF EXISTS prevent_audit_event_mutation();
    """))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_evidence_review_history', schema=None) as batch_op:
        batch_op.drop_index('uq_asset_evidence_review_history_reference', postgresql_where=sa.text('reference IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_review_history_reference'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_review_history_id'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_review_history_evidence_id'))

    op.drop_table('asset_evidence_review_history')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_receipts_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('payment_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reconciliations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_reconciliations_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_reconciliations_id'))

    op.drop_table('payment_reconciliations')
    with op.batch_alter_table('payment_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_audits_id'))

    op.drop_table('payment_audits')
    with op.batch_alter_table('passport_lifecycle_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passport_lifecycle_history_reference'))
        batch_op.drop_index(batch_op.f('ix_passport_lifecycle_history_passport_id'))
        batch_op.drop_index(batch_op.f('ix_passport_lifecycle_history_id'))

    op.drop_table('passport_lifecycle_history')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_payment_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_reference'))
        batch_op.drop_index(batch_op.f('ix_audit_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_passport_id'))
        batch_op.drop_index('ix_audit_events_occurred_at')
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_index(batch_op.f('ix_audit_events_asset_registry_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('asset_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_transactions_id'))

    op.drop_table('asset_transactions')
    with op.batch_alter_table('asset_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_evidence_storage_key'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_storage_backend'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_reference'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_passport_id'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_fingerprint_sha256'))
        batch_op.drop_index(batch_op.f('ix_asset_evidence_evidence_id'))

    op.drop_table('asset_evidence')
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_id'))

    op.drop_table('pricing')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('government_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_verifications_id'))
        batch_op.drop_index(batch_op.f('ix_government_verifications_asset_registry_id'))

    op.drop_table('government_verifications')
    with op.batch_alter_table('asset_passports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_passports_passport_id'))
        batch_op.drop_index(batch_op.f('ix_asset_passports_id'))
        batch_op.drop_index(batch_op.f('ix_asset_passports_asset_registry_id'))

    op.drop_table('asset_passports')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_key'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_id'))

    op.drop_table('stocks')
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lands_id'))

    op.drop_table('lands')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_asset_transaction_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('intellectual_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intellectual_properties_id'))

    op.drop_table('intellectual_properties')
    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_id'))

    op.drop_table('insurance')
    with op.batch_alter_table('gold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gold_id'))

    op.drop_table('gold')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_id'))

    op.drop_table('farms')
    with op.batch_alter_table('diamonds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diamonds_id'))

    op.drop_table('diamonds')
    with op.batch_alter_table('crypto_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crypto_wallets_id'))

    op.drop_table('crypto_wallets')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_id'))
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_id'))

    op.drop_table('businesses')
    with op.batch_alter_table('bonds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonds_id'))

    op.drop_table('bonds')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_id'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_id'))

    op.drop_table('assets')
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_registry_sal_id'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_id'))

    op.drop_table('asset_registry')
    # ### end Alembic commands ###
