from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.sql import func

from app.database.database import Base


class AssetRegistry(Base):

    __tablename__ = "asset_registry"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # Permanent SAL identity.
    #
    # Existing SAL IDs must NEVER be regenerated.
    # New SAL IDs are generated by SAL server-side.
    sal_id = Column(
        String,
        unique=True,
        index=True,
        nullable=True
    )

    asset_type = Column(
        String,
        nullable=False
    )

    # ID of the underlying specialized registry record.
    registry_id = Column(
        Integer,
        nullable=False
    )

    owner = Column(
        String,
        nullable=False
    )

    estimated_value = Column(
        Float,
        nullable=True
    )

    status = Column(
        String,
        default="Active"
    )

    # SAL verification means the asset has passed
    # SAL's own registration/verification process.
    #
    # This does NOT mean government ownership verification.
    sal_verification = Column(
        String,
        default="VERIFIED"
    )

    # Government verification remains separate.
    government_verification = Column(
        String,
        default="NOT_VERIFIED"
    )

    # Cryptographic anchoring/blockchain status.
    # This is NOT the source of legal ownership truth.
    blockchain_status = Column(
        String,
        default="PENDING"
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )

    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now()
    )
